------------------Pedido por parceiro-----------------------
CREATE OR REPLACE VIEW PEDIDO_PARCEIRO 
AS
SELECT NOME_PARCEIRO, ID_PEDIDO, VALOR_TOTAL FROM 
PARCEIRO NATURAL JOIN PEDIDO

CREATE OR REPLACE FUNCTION MOSTRAR_PEDIDOS_POR_PARCEIRO_2 (_ID_PARCEIRO INT)
RETURNS SETOF PEDIDO_PARCEIRO AS $$
BEGIN
	RETURN QUERY SELECT NOME_PARCEIRO, ID_PEDIDO, VALOR_TOTAL FROM 
	PARCEIRO NATURAL JOIN PEDIDO WHERE ID_PARCEIRO = _ID_PARCEIRO;
END;
$$
LANGUAGE 'plpgsql';

SELECT * FROM MOSTRAR_PEDIDOS_POR_PARCEIRO_2(2)

------------------------------------------------------------------

---------------------PEDRAS POR PEDIDOS --------------------------

CREATE OR REPLACE FUNCTION MOSTRAR_PEDRAS_POR_PEDIDO_2 (_ID_PEDIDO INT)
RETURNS TABLE (ID_DO_PEDIDO INT, ID_DA_PEDRA INT) AS $$

BEGIN
	RETURN QUERY SELECT ID_PEDIDO, ID_PEDRA FROM LISTA_PEDRAS_PEDIDO
	WHERE ID_PEDIDO = _ID_PEDIDO;
	
END;
$$
LANGUAGE 'plpgsql';

SELECT * FROM MOSTRAR_PEDRAS_POR_PEDIDO_2(2)

----------------------------------------------------------------------

-----------------PEDIDOS POR ANALISTA-------------------------------
CREATE OR REPLACE FUNCTION MOSTRAR_PEDIDO_POR_ANALISTA_2 (_ID_ANALISTA INT)
RETURNS TABLE (ID_DO_ANALISTA INT, NOME_DO_ANALISTA VARCHAR(20), ID_DO_PEDIDO INT) AS $$

BEGIN
	RETURN QUERY SELECT ANA.ID_ANALISTA, ANA.NOME, PE.ID_PEDIDO FROM ANALISTA ANA
	NATURAL JOIN PEDIDO PE
	WHERE ANA.ID_ANALISTA = _ID_ANALISTA;
END;
$$
LANGUAGE 'plpgsql';

SELECT * FROM MOSTRAR_PEDIDO_POR_ANALISTA_2(1)

-----------------------------------------------------------------------------------

----------------------RELATÓRIOS DE PEDRAS POR PERÍODO-------------------------


CREATE OR REPLACE FUNCTION FATURAMENTO_PEDRAS_POR_ID_3 (_ID_PEDRA INT, _DT_INICIAL DATE, _DT_FINAL DATE)
RETURNS TABLE (ID_DA_PEDRA INT, FATURAMENTO_POR_PERIODO NUMERIC) AS $$

BEGIN
		RETURN QUERY (
		SELECT ID_PEDRA, SUM(FATURAMENTO) 
		FROM LISTA_PEDRAS_PEDIDO 
		WHERE DATA_INICIAL >= _DT_INICIAL AND DATA_FINAL <= _DT_FINAL 	
		GROUP BY ID_PEDRA
		HAVING ID_PEDRA = _ID_PEDRA);
END;
$$
LANGUAGE 'plpgsql';

SELECT * FROM FATURAMENTO_PEDRAS_POR_ID_3(1, '2023-06-05', '2023-08-05')
------------------------------------------------------------------------