CREATE TABLE TIPO_PESSOA (
	ID_TIPO_PESSOA SERIAL PRIMARY KEY NOT NULL,
	DESCRICAO_TIPO_PESSOA VARCHAR(40) NOT NULL
);


CREATE TABLE METODO_DE_PAGAMENTO (
	ID_METODO_DE_PAGAMENTO SERIAL PRIMARY KEY NOT NULL,
	NOME_METODO_DE_PAGAMENTO VARCHAR(40) NOT NULL

);

CREATE TABLE PEDRA (
	ID_PEDRA SERIAL PRIMARY KEY NOT NULL,
	DESCRICAO_PEDRA VARCHAR(100) NOT NULL,
	TAMANHO FLOAT DEFAULT 3.0 NOT NULL,
	VALOR_DIARIA FLOAT NOT NULL

);

CREATE TABLE ANALISTA (
	ID_ANALISTA SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	CPF_ANALISTA INT NOT NULL,
	ENDERECO_ANALISTA VARCHAR(100) NOT NULL,
	SALARIO FLOAT NOT NULL

);
-- Validar CPF

CREATE TABLE PARCEIRO (
	ID_PARCEIRO SERIAL PRIMARY KEY NOT NULL,
	NOME_PARCEIRO VARCHAR(40) NOT NULL,
	CPF_CNPJ INT NOT NULL,
	TELEFONE INT NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	ENDERECO_PARCEIRO VARCHAR(100) NOT NULL,
	TIPO_PESSOA SERIAL NOT NULL REFERENCES TIPO_PESSOA
);


CREATE TABLE PEDIDO (
	ID_PEDIDO SERIAL PRIMARY KEY NOT NULL,
	ID_METODO_PAGAMENTO INT NOT NULL REFERENCES METODO_DE_PAGAMENTO,
	ID_PARCEIRO INT NOT NULL REFERENCES PARCEIRO,
	ID_ANALISTA INT NOT NULL REFERENCES ANALISTA,
	DATA_VENCIMENTO_PAGAMENTO_COMISSAO TIMESTAMP NOT NULL,
	DATA_PAGAMENTO_COMISSAO TIMESTAMP,
	VALOR_COMISSAO FLOAT DEFAULT 0.0,
	VALOR_TOTAL FLOAT DEFAULT 0.0 NOT NULL,	
	DATA_REGISTRO TIMESTAMP DEFAULT NOW(),
	NUMERO_NOTA SERIAL,
	DATA_PAGAMENTO TIMESTAMP
);


CREATE TABLE MULTA (
	ID_MULTA SERIAL PRIMARY KEY NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	ID_PEDIDO SERIAL NOT NULL REFERENCES PEDIDO,
	VALOR_MULTA FLOAT NOT NULL
	
	
);



CREATE TABLE LISTA_PEDRAS_PEDIDO (
	ID_PEDRA SERIAL NOT NULL REFERENCES PEDRA,
	ID_PEDIDO SERIAL NOT NULL REFERENCES PEDIDO,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL,
	FATURAMENTO FLOAT DEFAULT 0 NOT NULL,
	
	CONSTRAINT ID_PEDRA_PEDIDO PRIMARY KEY (ID_PEDRA, ID_PEDIDO)
);
