INSERT INTO TIPO_PESSOA VALUES 
(DEFAULT, 'PESSOA FÍSICA'), 
(DEFAULT, 'PESSOA JURIDICA');


INSERT INTO CARGO(NOME_CARGO, SALARIO) VALUES 
('ATENDENTE', 2500.00),
('GERENTE', 4600.00),
('DONO', 10500.00);

INSERT INTO ANALISTA VALUES
(DEFAULT, 'ROMERO', '10030812313', 'RUA CAPITÃO ADÃO DE CARVALHO', 3, DEFAULT, 'postgres');

INSERT INTO METODO_DE_PAGAMENTO VALUES 
(DEFAULT, 'ESPÉCIE'),
(DEFAULT, 'CRÉDITO'),
(DEFAULT, 'DÉBITO'),
(DEFAULT, 'PIX');


INSERT INTO PEDRA VALUES 
(DEFAULT, 'PEDRA S-01', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-02', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-03', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-04', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-05', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-01', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-02', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-03', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-04', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-05', DEFAULT, DEFAULT);

INSERT INTO TIPO_MULTA(DESCRICAO_TIPO_MULTA, VALOR_MULTA) VALUES 
('ATRASO NO PAGAMENTO DA COMISSÃO', 250.00),
('DANOS MATERIAS', 300.00),
('DANOS MORAIS', 300.00),
('OUTROS', 450.00);