INSERT INTO TIPO_PESSOA VALUES 
(DEFAULT, 'PESSOA FÍSICA'), 
(DEFAULT, 'PESSOA JURIDICA');

INSERT INTO ANALISTA VALUES (DEFAULT, 'MARIA ANA', '33879710368', 'RUA DO FACAO DE FORA', 1200.00);

INSERT INTO METODO_DE_PAGAMENTO VALUES 
(DEFAULT, 'ESPÉCIE'),
(DEFAULT, 'CRÉDITO'),
(DEFAULT, 'DÉBITO'),
(DEFAULT, 'PIX');


INSERT INTO PEDRA VALUES 
(DEFAULT, 'PEDRA S-01', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-02', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-03', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-04', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA S-05', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-01', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-02', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-03', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-04', DEFAULT, DEFAULT),
(DEFAULT, 'PEDRA N-05', DEFAULT, DEFAULT);
SELECT * FROM PEDRA;