
-- PRIVILÉGIOS DO ATENDENTE
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM ATENDENTE;

GRANT SELECT ON TIPO_PESSOA TO ATENDENTE;
GRANT SELECT ON TIPO_MULTA TO ATENDENTE;
GRANT SELECT ON METODO_DE_PAGAMENTO TO ATENDENTE;
GRANT SELECT ON PEDRA TO ATENDENTE;
GRANT SELECT ON ANALISTA TO ATENDENTE;


GRANT SELECT, INSERT, UPDATE ON PARCEIRO TO ATENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON LISTA_PEDRAS_PEDIDO TO ATENDENTE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PEDIDO TO ATENDENTE;
GRANT SELECT, INSERT ON MULTA TO ATENDENTE;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ATENDENTE;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ATENDENTE;

REVOKE EXECUTE ON FUNCTION CADASTRAR_ANALISTA FROM ATENDENTE;
-- REVOKE DELETE ON LISTA_PEDRAS_PEDIDO FROM ATENDENTE;


-- PRIVILÉGIOS DO GERENTE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO GERENTE;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO GERENTE;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO GERENTE;
REVOKE DELETE ON ANALISTA FROM GERENTE;
ALTER ROLE GERENTE WITH CREATEROLE;

-- PRIVILÉGIOS DO DONO
ALTER ROLE DONO SUPERUSER;


